version: '2'
services:
  database:
    image: mongo:3.0.15
    volumes:
      - ~/app_data/asset_manager/db:/data/db
  api-server:
    build: ./api
    volumes:
      - ./api:/var/www
    ports:
      - "3000:3000"
    environment:
      - APP_CUSTOM_API_KEY=non-secure-api-key
      - APP_DATABASE_NAME=app_default_database
      - APP_CREATE_API_KEY=true
      - APP_DATABASE_SEED=true
      - APP_CREATE_ADMIN_USER=true
      - APP_DATABASE_HOST=database
    depends_on:
      - database
  front-server:
    build: ./front_end
    volumes:
      - ./front_end:/var/www
    environment:
      - APP_SERVER_API_URI=http://api-server:3000/api/beta
    ports:
      - "80:80"
    depends_on:
      - api-server
      - database
